[project]
name = "ratball"
version = "0.1.0"
description = "Motion tracking and audio/visual telemetry platform for the RATBALL omni-treadmill system"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]
