ingestor:
  ip: 127.0.0.1
  gateway_port: 9595
  data_port_range_start: 30000
  data_port_range_end: 42000
  client_hello_binfmt: '>sId'
  handshake_binfmt: '>H'
bmi:
  ip: 127.0.0.1
  gateway_port: 8888
  data_port_range_start: 30000
  data_port_range_end: 42000
  comm_port: 36785
  listen_port: 36787
buffer:
  buffer_length: 10
  framerate: 30
audio:
  channels: 1
  format: S16_LE
  rate: 44100
speaker:
  channels: 1
  block_size: 4096
  amplitude: .5
sensor:
  i2c_addr:
    - 0x17
    - 0x67
  binfmt: '>4dI'
camera:
  ident:
    - 0
    - 1
data_paths:
  sensor: /mnt/extended/data_capture/sensor
  camera: /mnt/extended/data_capture/camera
  audio: /mnt/extended/data_capture/audio
  logs: /mnt/extended/data_capture/ratball.log

